### PR TITLE
Changing let to var 

### PR DESCRIPTION
**Pull request by MrHassanMurtaza**
"let" keyword wasn't introduced until ES6.

### CODE REVIEW

**Comment by ahmadawais** [comment]
Where exactly did you make a change?

**Comment by MrHassanMurtaza** [comment]
Oh, I should've mentioned it. 
I changed the "let" to "var" in "old way" of JS. It was mistakenly written as "let" instead of "var".

**Comment by MrHassanMurtaza** [comment]
Please check the screenshot.

selection_043

**Comment by ahmadawais** [comment]
@MrHassanMurtaza Thanks for that. How did you go about fixing it? Are you using Balsamiq? @MrSaqibAmeen check this! 

Also, this project hasn't launched yet so thanks for making it better already.

**Comment by MrHassanMurtaza** [comment]
@ahmadawais Yes, I go on to use Balsamiq to fix this up.

**Comment by ahmadawais** [comment]
Good stuff.

**Pull request merged**
